name: CI-CD
on:
  push:
    bransches:
      - master

  workflow_dispatch:

jobs:
  CI-CD:
    name: CI-CD
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - uses: actions/checkout@v2
      - name: CI-CD
        run: |
            chmod +x gitactions.sh
            ./gitactions.sh
