name: CI-CD
on:
  push:
    bransches:
      - master

  workflow_dispatch:

jobs:
  CI-CD:
    name: CI-CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: CI-CD
        run: |
            chmod +x gitactions.sh
            ./gitactions.sh
